### ISSUE TITLE
Noise addition

### ISSUE THREAD

**Issue by rcrehuet** [cavallilab/EntroLoss#1]
Hi,
Following the publication associated to this code, I'd like to add (gaussian) noise to the observables. Is there a way to do this with entroloss.py? 
Thanks!

**Comment by psolsson** [comment]
Ramon, the way we did it in the manuscript is simply by adding standard normal noise to the data after loading it. In the simplest case, where all the data have the same error stored in the variable std_dev, this may be done fx by modifying line 125 to:
 distances = distances + random.standard_normal(shape(distances))*std_dev

Hope it helps.

Cheers,
Simon

**Comment by rcrehuet** [comment]
Thanks!
